# Generated by Django 3.0.8 on 2020-09-04 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20200827_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='in_order',
            field=models.BooleanField(default=False),
        ),
    ]
