# Generated by Django 3.0.8 on 2020-09-04 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_offer_in_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='cover_image',
            field=models.CharField(default='https://store-images.s-microsoft.com/image/apps.28990.69531514236615003.8f0d03d6-6311-4c21-a151-834503c2901a.d629260e-2bc4-4588-950c-f278cbc22a64', max_length=500),
        ),
    ]
