# Generated by Django 3.0.8 on 2020-09-04 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_offer_cover_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='description',
        ),
        migrations.AddField(
            model_name='offer',
            name='price',
            field=models.CharField(default='199,99zł', max_length=10),
        ),
    ]
