# Generated by Django 3.0.8 on 2020-09-08 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20200904_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='cover_image',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='offer',
            name='price',
            field=models.FloatField(),
        ),
    ]
